// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Crypto int32

const (
	Crypto_SECP Crypto = 0
	Crypto_SM2  Crypto = 1
)

var Crypto_name = map[int32]string{
	0: "SECP",
	1: "SM2",
}
var Crypto_value = map[string]int32{
	"SECP": 0,
	"SM2":  1,
}

func (x Crypto) String() string {
	return proto.EnumName(Crypto_name, int32(x))
}
func (Crypto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_b45a58b2e0dadbea, []int{0}
}

type Transaction struct {
	To                   string   `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	Quota                uint64   `protobuf:"varint,3,opt,name=quota" json:"quota,omitempty"`
	ValidUntilBlock      uint64   `protobuf:"varint,4,opt,name=valid_until_block,json=validUntilBlock" json:"valid_until_block,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Value                uint64   `protobuf:"varint,6,opt,name=value" json:"value,omitempty"`
	ChainId              uint32   `protobuf:"varint,7,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Version              uint32   `protobuf:"varint,8,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_b45a58b2e0dadbea, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetQuota() uint64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *Transaction) GetValidUntilBlock() uint64 {
	if m != nil {
		return m.ValidUntilBlock
	}
	return 0
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type UnverifiedTransaction struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
	Signature            []byte       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Crypto               Crypto       `protobuf:"varint,3,opt,name=crypto,enum=Crypto" json:"crypto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UnverifiedTransaction) Reset()         { *m = UnverifiedTransaction{} }
func (m *UnverifiedTransaction) String() string { return proto.CompactTextString(m) }
func (*UnverifiedTransaction) ProtoMessage()    {}
func (*UnverifiedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_b45a58b2e0dadbea, []int{1}
}
func (m *UnverifiedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnverifiedTransaction.Unmarshal(m, b)
}
func (m *UnverifiedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnverifiedTransaction.Marshal(b, m, deterministic)
}
func (dst *UnverifiedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnverifiedTransaction.Merge(dst, src)
}
func (m *UnverifiedTransaction) XXX_Size() int {
	return xxx_messageInfo_UnverifiedTransaction.Size(m)
}
func (m *UnverifiedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_UnverifiedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_UnverifiedTransaction proto.InternalMessageInfo

func (m *UnverifiedTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *UnverifiedTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *UnverifiedTransaction) GetCrypto() Crypto {
	if m != nil {
		return m.Crypto
	}
	return Crypto_SECP
}

type SignedTransaction struct {
	TransactionWithSig   *UnverifiedTransaction `protobuf:"bytes,1,opt,name=transaction_with_sig,json=transactionWithSig" json:"transaction_with_sig,omitempty"`
	TxHash               []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Signer               []byte                 `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SignedTransaction) Reset()         { *m = SignedTransaction{} }
func (m *SignedTransaction) String() string { return proto.CompactTextString(m) }
func (*SignedTransaction) ProtoMessage()    {}
func (*SignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_b45a58b2e0dadbea, []int{2}
}
func (m *SignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedTransaction.Unmarshal(m, b)
}
func (m *SignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedTransaction.Marshal(b, m, deterministic)
}
func (dst *SignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedTransaction.Merge(dst, src)
}
func (m *SignedTransaction) XXX_Size() int {
	return xxx_messageInfo_SignedTransaction.Size(m)
}
func (m *SignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SignedTransaction proto.InternalMessageInfo

func (m *SignedTransaction) GetTransactionWithSig() *UnverifiedTransaction {
	if m != nil {
		return m.TransactionWithSig
	}
	return nil
}

func (m *SignedTransaction) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *SignedTransaction) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

type SendTransactionReq struct {
	Untx                 *UnverifiedTransaction `protobuf:"bytes,1,opt,name=untx" json:"untx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SendTransactionReq) Reset()         { *m = SendTransactionReq{} }
func (m *SendTransactionReq) String() string { return proto.CompactTextString(m) }
func (*SendTransactionReq) ProtoMessage()    {}
func (*SendTransactionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_b45a58b2e0dadbea, []int{3}
}
func (m *SendTransactionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionReq.Unmarshal(m, b)
}
func (m *SendTransactionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionReq.Marshal(b, m, deterministic)
}
func (dst *SendTransactionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionReq.Merge(dst, src)
}
func (m *SendTransactionReq) XXX_Size() int {
	return xxx_messageInfo_SendTransactionReq.Size(m)
}
func (m *SendTransactionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionReq proto.InternalMessageInfo

func (m *SendTransactionReq) GetUntx() *UnverifiedTransaction {
	if m != nil {
		return m.Untx
	}
	return nil
}

type SendTransactionRes struct {
	TxHash               []byte   `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionRes) Reset()         { *m = SendTransactionRes{} }
func (m *SendTransactionRes) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRes) ProtoMessage()    {}
func (*SendTransactionRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_b45a58b2e0dadbea, []int{4}
}
func (m *SendTransactionRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRes.Unmarshal(m, b)
}
func (m *SendTransactionRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRes.Marshal(b, m, deterministic)
}
func (dst *SendTransactionRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRes.Merge(dst, src)
}
func (m *SendTransactionRes) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRes.Size(m)
}
func (m *SendTransactionRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRes.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRes proto.InternalMessageInfo

func (m *SendTransactionRes) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

type PackTransactionsReq struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackTransactionsReq) Reset()         { *m = PackTransactionsReq{} }
func (m *PackTransactionsReq) String() string { return proto.CompactTextString(m) }
func (*PackTransactionsReq) ProtoMessage()    {}
func (*PackTransactionsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_b45a58b2e0dadbea, []int{5}
}
func (m *PackTransactionsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackTransactionsReq.Unmarshal(m, b)
}
func (m *PackTransactionsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackTransactionsReq.Marshal(b, m, deterministic)
}
func (dst *PackTransactionsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackTransactionsReq.Merge(dst, src)
}
func (m *PackTransactionsReq) XXX_Size() int {
	return xxx_messageInfo_PackTransactionsReq.Size(m)
}
func (m *PackTransactionsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PackTransactionsReq.DiscardUnknown(m)
}

var xxx_messageInfo_PackTransactionsReq proto.InternalMessageInfo

func (m *PackTransactionsReq) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type PackTransactionsRes struct {
	TxHashes             [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackTransactionsRes) Reset()         { *m = PackTransactionsRes{} }
func (m *PackTransactionsRes) String() string { return proto.CompactTextString(m) }
func (*PackTransactionsRes) ProtoMessage()    {}
func (*PackTransactionsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_b45a58b2e0dadbea, []int{6}
}
func (m *PackTransactionsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackTransactionsRes.Unmarshal(m, b)
}
func (m *PackTransactionsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackTransactionsRes.Marshal(b, m, deterministic)
}
func (dst *PackTransactionsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackTransactionsRes.Merge(dst, src)
}
func (m *PackTransactionsRes) XXX_Size() int {
	return xxx_messageInfo_PackTransactionsRes.Size(m)
}
func (m *PackTransactionsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PackTransactionsRes.DiscardUnknown(m)
}

var xxx_messageInfo_PackTransactionsRes proto.InternalMessageInfo

func (m *PackTransactionsRes) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*UnverifiedTransaction)(nil), "UnverifiedTransaction")
	proto.RegisterType((*SignedTransaction)(nil), "SignedTransaction")
	proto.RegisterType((*SendTransactionReq)(nil), "SendTransactionReq")
	proto.RegisterType((*SendTransactionRes)(nil), "SendTransactionRes")
	proto.RegisterType((*PackTransactionsReq)(nil), "PackTransactionsReq")
	proto.RegisterType((*PackTransactionsRes)(nil), "PackTransactionsRes")
	proto.RegisterEnum("Crypto", Crypto_name, Crypto_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	SendTransaction(ctx context.Context, in *SendTransactionReq, opts ...grpc.CallOption) (*SendTransactionRes, error)
	PackTransactions(ctx context.Context, in *PackTransactionsReq, opts ...grpc.CallOption) (*PackTransactionsRes, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) SendTransaction(ctx context.Context, in *SendTransactionReq, opts ...grpc.CallOption) (*SendTransactionRes, error) {
	out := new(SendTransactionRes)
	err := c.cc.Invoke(ctx, "/Auth/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) PackTransactions(ctx context.Context, in *PackTransactionsReq, opts ...grpc.CallOption) (*PackTransactionsRes, error) {
	out := new(PackTransactionsRes)
	err := c.cc.Invoke(ctx, "/Auth/PackTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	SendTransaction(context.Context, *SendTransactionReq) (*SendTransactionRes, error)
	PackTransactions(context.Context, *PackTransactionsReq) (*PackTransactionsRes, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SendTransaction(ctx, req.(*SendTransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_PackTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackTransactionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).PackTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/PackTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).PackTransactions(ctx, req.(*PackTransactionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTransaction",
			Handler:    _Auth_SendTransaction_Handler,
		},
		{
			MethodName: "PackTransactions",
			Handler:    _Auth_PackTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_b45a58b2e0dadbea) }

var fileDescriptor_auth_b45a58b2e0dadbea = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x51, 0x6b, 0xdb, 0x3e,
	0x14, 0xc5, 0xa3, 0xc4, 0xb5, 0x93, 0x9b, 0xfc, 0xdb, 0xf4, 0x36, 0xff, 0x4c, 0x6b, 0x07, 0x0b,
	0x7e, 0x0a, 0x81, 0xfa, 0x21, 0x7b, 0x1e, 0x74, 0x2b, 0x83, 0xee, 0x61, 0x50, 0x94, 0x95, 0x3d,
	0x1a, 0xd5, 0xd1, 0x22, 0xd1, 0x20, 0xb5, 0x96, 0x9c, 0x65, 0x5f, 0x60, 0x7b, 0xdb, 0xa7, 0xdb,
	0x07, 0x1a, 0x96, 0x0d, 0x75, 0x3b, 0xc3, 0xde, 0x72, 0x8e, 0x4e, 0xce, 0xfd, 0xdd, 0x0b, 0x06,
	0xe0, 0x85, 0x93, 0xc9, 0x7d, 0x6e, 0x9c, 0x89, 0x7f, 0x13, 0x18, 0x7e, 0xce, 0xb9, 0xb6, 0x3c,
	0x73, 0xca, 0x68, 0x3c, 0x84, 0xae, 0x33, 0x94, 0xcc, 0xc8, 0x7c, 0xc0, 0xba, 0xce, 0xe0, 0x04,
	0x0e, 0xb4, 0xd1, 0x99, 0xa0, 0x5d, 0x6f, 0x55, 0xa2, 0x74, 0x1f, 0x0a, 0xe3, 0x38, 0xed, 0xcd,
	0xc8, 0x3c, 0x60, 0x95, 0xc0, 0x05, 0x1c, 0xef, 0xf8, 0x56, 0xad, 0xd3, 0x42, 0x3b, 0xb5, 0x4d,
	0x6f, 0xb7, 0x26, 0xbb, 0xa3, 0x81, 0x4f, 0x1c, 0xf9, 0x87, 0x9b, 0xd2, 0x7f, 0x5f, 0xda, 0x88,
	0x10, 0xac, 0xb9, 0xe3, 0xf4, 0x60, 0x46, 0xe6, 0x23, 0xe6, 0x7f, 0x97, 0xad, 0x3b, 0xbe, 0x2d,
	0x04, 0x0d, 0xab, 0x56, 0x2f, 0xf0, 0x25, 0xf4, 0x33, 0xc9, 0x95, 0x4e, 0xd5, 0x9a, 0x46, 0x33,
	0x32, 0xff, 0x8f, 0x45, 0x5e, 0x7f, 0x5c, 0x23, 0x85, 0x68, 0x27, 0x72, 0xab, 0x8c, 0xa6, 0xfd,
	0xea, 0xa5, 0x96, 0xf1, 0x0f, 0x02, 0xff, 0xdf, 0xe8, 0x9d, 0xc8, 0xd5, 0x57, 0x25, 0xd6, 0xcd,
	0x05, 0x13, 0x18, 0xba, 0x47, 0xe9, 0x37, 0x1d, 0x2e, 0x47, 0x49, 0x23, 0xc2, 0x9a, 0x01, 0x7c,
	0x05, 0x03, 0xab, 0x36, 0x9a, 0xbb, 0x22, 0xaf, 0x8e, 0x30, 0x62, 0x8f, 0x06, 0xbe, 0x86, 0x30,
	0xcb, 0xbf, 0xdf, 0x3b, 0xe3, 0x2f, 0x71, 0xb8, 0x8c, 0x92, 0x4b, 0x2f, 0x59, 0x6d, 0xc7, 0xbf,
	0x08, 0x1c, 0xaf, 0xd4, 0x46, 0x3f, 0x85, 0xb8, 0x82, 0x49, 0x63, 0x46, 0xfa, 0x4d, 0x39, 0x99,
	0x5a, 0xb5, 0xa9, 0x69, 0xa6, 0x49, 0x2b, 0x3a, 0xc3, 0xc6, 0x7f, 0xbe, 0x28, 0x27, 0x57, 0x6a,
	0x83, 0x2f, 0x20, 0x72, 0xfb, 0x54, 0x72, 0x2b, 0x6b, 0xb8, 0xd0, 0xed, 0xaf, 0xb8, 0x95, 0x38,
	0x85, 0xb0, 0xc4, 0x14, 0xb9, 0x27, 0x1b, 0xb1, 0x5a, 0xc5, 0x17, 0x80, 0x2b, 0xa1, 0x9f, 0xf4,
	0x8a, 0x07, 0x5c, 0x40, 0x50, 0x68, 0xb7, 0xff, 0x07, 0x80, 0xcf, 0xc4, 0xe7, 0x2d, 0x0d, 0xb6,
	0x09, 0x42, 0x9a, 0x20, 0xf1, 0x39, 0x9c, 0x5c, 0xf3, 0xec, 0xae, 0x11, 0xb7, 0xe5, 0xc4, 0x29,
	0x84, 0x52, 0xa8, 0x8d, 0x74, 0x3e, 0x1e, 0xb0, 0x5a, 0xc5, 0xcb, 0xb6, 0xb8, 0xc5, 0x33, 0x18,
	0xd4, 0xf5, 0xc2, 0x52, 0x32, 0xeb, 0xcd, 0x47, 0xac, 0x5f, 0x0d, 0x10, 0x76, 0x71, 0x06, 0x61,
	0x75, 0x76, 0xec, 0x43, 0xb0, 0xfa, 0x70, 0x79, 0x3d, 0xee, 0x60, 0x04, 0xbd, 0xd5, 0xa7, 0xe5,
	0x98, 0x2c, 0x7f, 0x12, 0x08, 0xde, 0x15, 0x4e, 0xe2, 0x5b, 0x38, 0x7a, 0xc6, 0x8d, 0x27, 0xc9,
	0xdf, 0xb7, 0x38, 0x6d, 0x31, 0x6d, 0xdc, 0xc1, 0x0b, 0x18, 0x3f, 0x07, 0xc3, 0x49, 0xd2, 0xb2,
	0xda, 0x69, 0x9b, 0x6b, 0xe3, 0xce, 0x6d, 0xe8, 0x3f, 0xb9, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x03, 0xbc, 0xb7, 0xc1, 0x80, 0x03, 0x00, 0x00,
}
