// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consensus.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Proposal struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
	Islock               bool     `protobuf:"varint,2,opt,name=islock" json:"islock,omitempty"`
	LockRound            uint64   `protobuf:"varint,3,opt,name=lock_round,json=lockRound" json:"lock_round,omitempty"`
	LockVotes            []*Vote  `protobuf:"bytes,4,rep,name=lock_votes,json=lockVotes" json:"lock_votes,omitempty"`
	Round                uint64   `protobuf:"varint,5,opt,name=round" json:"round,omitempty"`
	Height               uint64   `protobuf:"varint,6,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a66dfad8f1bf55d0, []int{0}
}
func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (dst *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(dst, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Proposal) GetIslock() bool {
	if m != nil {
		return m.Islock
	}
	return false
}

func (m *Proposal) GetLockRound() uint64 {
	if m != nil {
		return m.LockRound
	}
	return 0
}

func (m *Proposal) GetLockVotes() []*Vote {
	if m != nil {
		return m.LockVotes
	}
	return nil
}

func (m *Proposal) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Proposal) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Vote struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Proposal             []byte   `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a66dfad8f1bf55d0, []int{1}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (dst *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(dst, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Vote) GetProposal() []byte {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *Vote) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SignedProposal struct {
	Proposal             *Proposal `protobuf:"bytes,1,opt,name=proposal" json:"proposal,omitempty"`
	Signature            []byte    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignedProposal) Reset()         { *m = SignedProposal{} }
func (m *SignedProposal) String() string { return proto.CompactTextString(m) }
func (*SignedProposal) ProtoMessage()    {}
func (*SignedProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a66dfad8f1bf55d0, []int{2}
}
func (m *SignedProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedProposal.Unmarshal(m, b)
}
func (m *SignedProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedProposal.Marshal(b, m, deterministic)
}
func (dst *SignedProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedProposal.Merge(dst, src)
}
func (m *SignedProposal) XXX_Size() int {
	return xxx_messageInfo_SignedProposal.Size(m)
}
func (m *SignedProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedProposal.DiscardUnknown(m)
}

var xxx_messageInfo_SignedProposal proto.InternalMessageInfo

func (m *SignedProposal) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *SignedProposal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Proposal)(nil), "Proposal")
	proto.RegisterType((*Vote)(nil), "Vote")
	proto.RegisterType((*SignedProposal)(nil), "SignedProposal")
}

func init() { proto.RegisterFile("consensus.proto", fileDescriptor_consensus_a66dfad8f1bf55d0) }

var fileDescriptor_consensus_a66dfad8f1bf55d0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xdf, 0x4a, 0x84, 0x40,
	0x14, 0xc6, 0x71, 0x57, 0x45, 0x8f, 0x52, 0x30, 0x44, 0xc8, 0xb2, 0x81, 0x48, 0x81, 0x57, 0x5e,
	0x6c, 0x6f, 0xd0, 0x13, 0xc4, 0x44, 0xd1, 0x5d, 0xb8, 0x3a, 0xe8, 0xd0, 0x32, 0x47, 0xe6, 0x8c,
	0xbd, 0x58, 0x2f, 0x18, 0xf3, 0xa7, 0x2d, 0x82, 0xae, 0xf4, 0xf7, 0x7d, 0xf3, 0x9d, 0x39, 0xf3,
	0xc1, 0xe5, 0x80, 0x8a, 0x84, 0xa2, 0x95, 0xba, 0x45, 0xa3, 0xc1, 0x5d, 0x31, 0xcc, 0xbd, 0x54,
	0x1e, 0x9a, 0xcf, 0x08, 0xb2, 0x47, 0x8d, 0x0b, 0x52, 0x7f, 0x62, 0x7b, 0x48, 0x8e, 0x27, 0x1c,
	0xde, 0xab, 0xa8, 0x8e, 0xda, 0xe2, 0x90, 0x76, 0x0f, 0x96, 0xb8, 0x17, 0xd9, 0x35, 0xa4, 0x92,
	0x9c, 0xbd, 0xa9, 0xa3, 0x36, 0xe3, 0x81, 0xd8, 0x0d, 0x80, 0xfd, 0xbe, 0x69, 0x5c, 0xd5, 0x58,
	0x6d, 0xeb, 0xa8, 0x8d, 0x79, 0xee, 0x82, 0x56, 0x60, 0xb7, 0xc1, 0xfe, 0x40, 0x23, 0xa8, 0x8a,
	0xeb, 0x6d, 0x5b, 0x1c, 0x92, 0xee, 0x05, 0x8d, 0xf0, 0xa7, 0xec, 0x1f, 0xb1, 0x2b, 0x48, 0x7c,
	0x3e, 0x71, 0x79, 0x0f, 0xf6, 0xca, 0x59, 0xc8, 0x69, 0x36, 0x55, 0xea, 0xe4, 0x40, 0xcd, 0x2b,
	0xc4, 0x36, 0x66, 0x7d, 0x12, 0x6a, 0x14, 0xda, 0x6d, 0x5c, 0xf2, 0x40, 0x6c, 0x07, 0xd9, 0x12,
	0x1e, 0xe5, 0x96, 0x2d, 0xf9, 0x99, 0xd9, 0x1e, 0x72, 0x92, 0x93, 0xea, 0xcd, 0xaa, 0x85, 0xdb,
	0xb6, 0xe4, 0x3f, 0x42, 0xf3, 0x0c, 0x17, 0x4f, 0x72, 0x52, 0x62, 0x3c, 0x97, 0x72, 0xf7, 0x6b,
	0x96, 0xef, 0x25, 0xef, 0xbe, 0xcd, 0xff, 0xc6, 0x6e, 0xfe, 0x8c, 0x3d, 0xa6, 0xae, 0xed, 0xfb,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x0e, 0x6a, 0x30, 0x8d, 0x01, 0x00, 0x00,
}
