// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Crypto int32

const (
	Crypto_SECP Crypto = 0
	Crypto_SM2  Crypto = 1
)

var Crypto_name = map[int32]string{
	0: "SECP",
	1: "SM2",
}
var Crypto_value = map[string]int32{
	"SECP": 0,
	"SM2":  1,
}

func (x Crypto) String() string {
	return proto.EnumName(Crypto_name, int32(x))
}
func (Crypto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{0}
}

type Transaction struct {
	To                   string   `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	Quota                uint64   `protobuf:"varint,3,opt,name=quota" json:"quota,omitempty"`
	ValidUntilBlock      uint64   `protobuf:"varint,4,opt,name=valid_until_block,json=validUntilBlock" json:"valid_until_block,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Value                []byte   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	ChainId              uint32   `protobuf:"varint,7,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Version              uint32   `protobuf:"varint,8,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetQuota() uint64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *Transaction) GetValidUntilBlock() uint64 {
	if m != nil {
		return m.ValidUntilBlock
	}
	return 0
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type UnverifiedTransaction struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
	Signature            []byte       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Crypto               Crypto       `protobuf:"varint,3,opt,name=crypto,enum=Crypto" json:"crypto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UnverifiedTransaction) Reset()         { *m = UnverifiedTransaction{} }
func (m *UnverifiedTransaction) String() string { return proto.CompactTextString(m) }
func (*UnverifiedTransaction) ProtoMessage()    {}
func (*UnverifiedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{1}
}
func (m *UnverifiedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnverifiedTransaction.Unmarshal(m, b)
}
func (m *UnverifiedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnverifiedTransaction.Marshal(b, m, deterministic)
}
func (dst *UnverifiedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnverifiedTransaction.Merge(dst, src)
}
func (m *UnverifiedTransaction) XXX_Size() int {
	return xxx_messageInfo_UnverifiedTransaction.Size(m)
}
func (m *UnverifiedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_UnverifiedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_UnverifiedTransaction proto.InternalMessageInfo

func (m *UnverifiedTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *UnverifiedTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *UnverifiedTransaction) GetCrypto() Crypto {
	if m != nil {
		return m.Crypto
	}
	return Crypto_SECP
}

type SignedTransaction struct {
	TransactionWithSig   *UnverifiedTransaction `protobuf:"bytes,1,opt,name=transaction_with_sig,json=transactionWithSig" json:"transaction_with_sig,omitempty"`
	TxHash               []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Signer               []byte                 `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SignedTransaction) Reset()         { *m = SignedTransaction{} }
func (m *SignedTransaction) String() string { return proto.CompactTextString(m) }
func (*SignedTransaction) ProtoMessage()    {}
func (*SignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{2}
}
func (m *SignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedTransaction.Unmarshal(m, b)
}
func (m *SignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedTransaction.Marshal(b, m, deterministic)
}
func (dst *SignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedTransaction.Merge(dst, src)
}
func (m *SignedTransaction) XXX_Size() int {
	return xxx_messageInfo_SignedTransaction.Size(m)
}
func (m *SignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SignedTransaction proto.InternalMessageInfo

func (m *SignedTransaction) GetTransactionWithSig() *UnverifiedTransaction {
	if m != nil {
		return m.TransactionWithSig
	}
	return nil
}

func (m *SignedTransaction) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *SignedTransaction) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

type AddUnverifyTxReq struct {
	Untx                 *UnverifiedTransaction `protobuf:"bytes,1,opt,name=untx" json:"untx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AddUnverifyTxReq) Reset()         { *m = AddUnverifyTxReq{} }
func (m *AddUnverifyTxReq) String() string { return proto.CompactTextString(m) }
func (*AddUnverifyTxReq) ProtoMessage()    {}
func (*AddUnverifyTxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{3}
}
func (m *AddUnverifyTxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUnverifyTxReq.Unmarshal(m, b)
}
func (m *AddUnverifyTxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUnverifyTxReq.Marshal(b, m, deterministic)
}
func (dst *AddUnverifyTxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUnverifyTxReq.Merge(dst, src)
}
func (m *AddUnverifyTxReq) XXX_Size() int {
	return xxx_messageInfo_AddUnverifyTxReq.Size(m)
}
func (m *AddUnverifyTxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUnverifyTxReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUnverifyTxReq proto.InternalMessageInfo

func (m *AddUnverifyTxReq) GetUntx() *UnverifiedTransaction {
	if m != nil {
		return m.Untx
	}
	return nil
}

type AddUnverifyTxRes struct {
	TxHash               []byte   `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUnverifyTxRes) Reset()         { *m = AddUnverifyTxRes{} }
func (m *AddUnverifyTxRes) String() string { return proto.CompactTextString(m) }
func (*AddUnverifyTxRes) ProtoMessage()    {}
func (*AddUnverifyTxRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{4}
}
func (m *AddUnverifyTxRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUnverifyTxRes.Unmarshal(m, b)
}
func (m *AddUnverifyTxRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUnverifyTxRes.Marshal(b, m, deterministic)
}
func (dst *AddUnverifyTxRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUnverifyTxRes.Merge(dst, src)
}
func (m *AddUnverifyTxRes) XXX_Size() int {
	return xxx_messageInfo_AddUnverifyTxRes.Size(m)
}
func (m *AddUnverifyTxRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUnverifyTxRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddUnverifyTxRes proto.InternalMessageInfo

func (m *AddUnverifyTxRes) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

type VerifyTxHashesReq struct {
	TxHashes             [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTxHashesReq) Reset()         { *m = VerifyTxHashesReq{} }
func (m *VerifyTxHashesReq) String() string { return proto.CompactTextString(m) }
func (*VerifyTxHashesReq) ProtoMessage()    {}
func (*VerifyTxHashesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{5}
}
func (m *VerifyTxHashesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTxHashesReq.Unmarshal(m, b)
}
func (m *VerifyTxHashesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTxHashesReq.Marshal(b, m, deterministic)
}
func (dst *VerifyTxHashesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTxHashesReq.Merge(dst, src)
}
func (m *VerifyTxHashesReq) XXX_Size() int {
	return xxx_messageInfo_VerifyTxHashesReq.Size(m)
}
func (m *VerifyTxHashesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTxHashesReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTxHashesReq proto.InternalMessageInfo

func (m *VerifyTxHashesReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

type GetTxFromPoolReq struct {
	QuotaLimit           uint64   `protobuf:"varint,1,opt,name=quota_limit,json=quotaLimit" json:"quota_limit,omitempty"`
	TxCount              uint32   `protobuf:"varint,2,opt,name=tx_count,json=txCount" json:"tx_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxFromPoolReq) Reset()         { *m = GetTxFromPoolReq{} }
func (m *GetTxFromPoolReq) String() string { return proto.CompactTextString(m) }
func (*GetTxFromPoolReq) ProtoMessage()    {}
func (*GetTxFromPoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{6}
}
func (m *GetTxFromPoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxFromPoolReq.Unmarshal(m, b)
}
func (m *GetTxFromPoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxFromPoolReq.Marshal(b, m, deterministic)
}
func (dst *GetTxFromPoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxFromPoolReq.Merge(dst, src)
}
func (m *GetTxFromPoolReq) XXX_Size() int {
	return xxx_messageInfo_GetTxFromPoolReq.Size(m)
}
func (m *GetTxFromPoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxFromPoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxFromPoolReq proto.InternalMessageInfo

func (m *GetTxFromPoolReq) GetQuotaLimit() uint64 {
	if m != nil {
		return m.QuotaLimit
	}
	return 0
}

func (m *GetTxFromPoolReq) GetTxCount() uint32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

type EnsureFromPoolReq struct {
	NodeId               uint32   `protobuf:"varint,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	QuotaUsed            uint64   `protobuf:"varint,2,opt,name=quota_used,json=quotaUsed" json:"quota_used,omitempty"`
	TxHashes             [][]byte `protobuf:"bytes,3,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnsureFromPoolReq) Reset()         { *m = EnsureFromPoolReq{} }
func (m *EnsureFromPoolReq) String() string { return proto.CompactTextString(m) }
func (*EnsureFromPoolReq) ProtoMessage()    {}
func (*EnsureFromPoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{7}
}
func (m *EnsureFromPoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnsureFromPoolReq.Unmarshal(m, b)
}
func (m *EnsureFromPoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnsureFromPoolReq.Marshal(b, m, deterministic)
}
func (dst *EnsureFromPoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnsureFromPoolReq.Merge(dst, src)
}
func (m *EnsureFromPoolReq) XXX_Size() int {
	return xxx_messageInfo_EnsureFromPoolReq.Size(m)
}
func (m *EnsureFromPoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnsureFromPoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnsureFromPoolReq proto.InternalMessageInfo

func (m *EnsureFromPoolReq) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *EnsureFromPoolReq) GetQuotaUsed() uint64 {
	if m != nil {
		return m.QuotaUsed
	}
	return 0
}

func (m *EnsureFromPoolReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

type GetTxFromPoolRes struct {
	TxHashes             [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	QuotaUsed            uint64   `protobuf:"varint,2,opt,name=quota_used,json=quotaUsed" json:"quota_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxFromPoolRes) Reset()         { *m = GetTxFromPoolRes{} }
func (m *GetTxFromPoolRes) String() string { return proto.CompactTextString(m) }
func (*GetTxFromPoolRes) ProtoMessage()    {}
func (*GetTxFromPoolRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{8}
}
func (m *GetTxFromPoolRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxFromPoolRes.Unmarshal(m, b)
}
func (m *GetTxFromPoolRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxFromPoolRes.Marshal(b, m, deterministic)
}
func (dst *GetTxFromPoolRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxFromPoolRes.Merge(dst, src)
}
func (m *GetTxFromPoolRes) XXX_Size() int {
	return xxx_messageInfo_GetTxFromPoolRes.Size(m)
}
func (m *GetTxFromPoolRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxFromPoolRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxFromPoolRes proto.InternalMessageInfo

func (m *GetTxFromPoolRes) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *GetTxFromPoolRes) GetQuotaUsed() uint64 {
	if m != nil {
		return m.QuotaUsed
	}
	return 0
}

type ClearPoolReq struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearPoolReq) Reset()         { *m = ClearPoolReq{} }
func (m *ClearPoolReq) String() string { return proto.CompactTextString(m) }
func (*ClearPoolReq) ProtoMessage()    {}
func (*ClearPoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{9}
}
func (m *ClearPoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearPoolReq.Unmarshal(m, b)
}
func (m *ClearPoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearPoolReq.Marshal(b, m, deterministic)
}
func (dst *ClearPoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearPoolReq.Merge(dst, src)
}
func (m *ClearPoolReq) XXX_Size() int {
	return xxx_messageInfo_ClearPoolReq.Size(m)
}
func (m *ClearPoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearPoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClearPoolReq proto.InternalMessageInfo

func (m *ClearPoolReq) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type EnsureHashesReq struct {
	NodeId               uint32   `protobuf:"varint,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	TxHashes             [][]byte `protobuf:"bytes,2,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnsureHashesReq) Reset()         { *m = EnsureHashesReq{} }
func (m *EnsureHashesReq) String() string { return proto.CompactTextString(m) }
func (*EnsureHashesReq) ProtoMessage()    {}
func (*EnsureHashesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{10}
}
func (m *EnsureHashesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnsureHashesReq.Unmarshal(m, b)
}
func (m *EnsureHashesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnsureHashesReq.Marshal(b, m, deterministic)
}
func (dst *EnsureHashesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnsureHashesReq.Merge(dst, src)
}
func (m *EnsureHashesReq) XXX_Size() int {
	return xxx_messageInfo_EnsureHashesReq.Size(m)
}
func (m *EnsureHashesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnsureHashesReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnsureHashesReq proto.InternalMessageInfo

func (m *EnsureHashesReq) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *EnsureHashesReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

type EnsureHashesRes struct {
	TxHashes             [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnsureHashesRes) Reset()         { *m = EnsureHashesRes{} }
func (m *EnsureHashesRes) String() string { return proto.CompactTextString(m) }
func (*EnsureHashesRes) ProtoMessage()    {}
func (*EnsureHashesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_848894963f0d413a, []int{11}
}
func (m *EnsureHashesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnsureHashesRes.Unmarshal(m, b)
}
func (m *EnsureHashesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnsureHashesRes.Marshal(b, m, deterministic)
}
func (dst *EnsureHashesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnsureHashesRes.Merge(dst, src)
}
func (m *EnsureHashesRes) XXX_Size() int {
	return xxx_messageInfo_EnsureHashesRes.Size(m)
}
func (m *EnsureHashesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EnsureHashesRes.DiscardUnknown(m)
}

var xxx_messageInfo_EnsureHashesRes proto.InternalMessageInfo

func (m *EnsureHashesRes) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*UnverifiedTransaction)(nil), "UnverifiedTransaction")
	proto.RegisterType((*SignedTransaction)(nil), "SignedTransaction")
	proto.RegisterType((*AddUnverifyTxReq)(nil), "AddUnverifyTxReq")
	proto.RegisterType((*AddUnverifyTxRes)(nil), "AddUnverifyTxRes")
	proto.RegisterType((*VerifyTxHashesReq)(nil), "VerifyTxHashesReq")
	proto.RegisterType((*GetTxFromPoolReq)(nil), "GetTxFromPoolReq")
	proto.RegisterType((*EnsureFromPoolReq)(nil), "EnsureFromPoolReq")
	proto.RegisterType((*GetTxFromPoolRes)(nil), "GetTxFromPoolRes")
	proto.RegisterType((*ClearPoolReq)(nil), "ClearPoolReq")
	proto.RegisterType((*EnsureHashesReq)(nil), "EnsureHashesReq")
	proto.RegisterType((*EnsureHashesRes)(nil), "EnsureHashesRes")
	proto.RegisterEnum("Crypto", Crypto_name, Crypto_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	AddUnverifyTx(ctx context.Context, in *AddUnverifyTxReq, opts ...grpc.CallOption) (*AddUnverifyTxRes, error)
	GetTxFromPool(ctx context.Context, in *GetTxFromPoolReq, opts ...grpc.CallOption) (*GetTxFromPoolRes, error)
	EnsureFromPool(ctx context.Context, in *EnsureFromPoolReq, opts ...grpc.CallOption) (*Empty, error)
	ClearPool(ctx context.Context, in *ClearPoolReq, opts ...grpc.CallOption) (*Empty, error)
	EnsureHashes(ctx context.Context, in *EnsureHashesReq, opts ...grpc.CallOption) (*EnsureHashesRes, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AddUnverifyTx(ctx context.Context, in *AddUnverifyTxReq, opts ...grpc.CallOption) (*AddUnverifyTxRes, error) {
	out := new(AddUnverifyTxRes)
	err := c.cc.Invoke(ctx, "/Auth/AddUnverifyTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetTxFromPool(ctx context.Context, in *GetTxFromPoolReq, opts ...grpc.CallOption) (*GetTxFromPoolRes, error) {
	out := new(GetTxFromPoolRes)
	err := c.cc.Invoke(ctx, "/Auth/GetTxFromPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) EnsureFromPool(ctx context.Context, in *EnsureFromPoolReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Auth/EnsureFromPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ClearPool(ctx context.Context, in *ClearPoolReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Auth/ClearPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) EnsureHashes(ctx context.Context, in *EnsureHashesReq, opts ...grpc.CallOption) (*EnsureHashesRes, error) {
	out := new(EnsureHashesRes)
	err := c.cc.Invoke(ctx, "/Auth/EnsureHashes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	AddUnverifyTx(context.Context, *AddUnverifyTxReq) (*AddUnverifyTxRes, error)
	GetTxFromPool(context.Context, *GetTxFromPoolReq) (*GetTxFromPoolRes, error)
	EnsureFromPool(context.Context, *EnsureFromPoolReq) (*Empty, error)
	ClearPool(context.Context, *ClearPoolReq) (*Empty, error)
	EnsureHashes(context.Context, *EnsureHashesReq) (*EnsureHashesRes, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_AddUnverifyTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUnverifyTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AddUnverifyTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/AddUnverifyTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AddUnverifyTx(ctx, req.(*AddUnverifyTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetTxFromPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxFromPoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetTxFromPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/GetTxFromPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetTxFromPool(ctx, req.(*GetTxFromPoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_EnsureFromPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureFromPoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).EnsureFromPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/EnsureFromPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).EnsureFromPool(ctx, req.(*EnsureFromPoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ClearPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearPoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ClearPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/ClearPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ClearPool(ctx, req.(*ClearPoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_EnsureHashes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureHashesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).EnsureHashes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/EnsureHashes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).EnsureHashes(ctx, req.(*EnsureHashesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUnverifyTx",
			Handler:    _Auth_AddUnverifyTx_Handler,
		},
		{
			MethodName: "GetTxFromPool",
			Handler:    _Auth_GetTxFromPool_Handler,
		},
		{
			MethodName: "EnsureFromPool",
			Handler:    _Auth_EnsureFromPool_Handler,
		},
		{
			MethodName: "ClearPool",
			Handler:    _Auth_ClearPool_Handler,
		},
		{
			MethodName: "EnsureHashes",
			Handler:    _Auth_EnsureHashes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_848894963f0d413a) }

var fileDescriptor_auth_848894963f0d413a = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0xda, 0x2c, 0x69, 0x6f, 0xd3, 0xad, 0xb5, 0xc6, 0x16, 0x3a, 0xd0, 0xaa, 0x08, 0xa1,
	0x6a, 0x48, 0x11, 0x2a, 0x48, 0xbc, 0x21, 0x8d, 0x6a, 0x6c, 0x93, 0x00, 0x4d, 0xee, 0x06, 0x8f,
	0x51, 0xd6, 0x98, 0xc6, 0x22, 0xb5, 0xb7, 0xd8, 0x29, 0xd9, 0x3b, 0xe2, 0x91, 0x5f, 0xc7, 0x0f,
	0x42, 0x76, 0x32, 0x96, 0xb6, 0xb0, 0xbd, 0xf5, 0x1c, 0xdf, 0x8f, 0x73, 0x4f, 0x8f, 0x02, 0x10,
	0x66, 0x32, 0xf6, 0xaf, 0x52, 0x2e, 0x79, 0xdf, 0x99, 0xf2, 0xf9, 0x9c, 0xb3, 0x02, 0x79, 0xbf,
	0x0d, 0x68, 0x9f, 0xa7, 0x21, 0x13, 0xe1, 0x54, 0x52, 0xce, 0xd0, 0x26, 0xd4, 0x25, 0x77, 0x8d,
	0x81, 0x31, 0x6c, 0xe1, 0xba, 0xe4, 0x68, 0x1b, 0x36, 0x18, 0x67, 0x53, 0xe2, 0xd6, 0x35, 0x55,
	0x00, 0xc5, 0x5e, 0x67, 0x5c, 0x86, 0x6e, 0x63, 0x60, 0x0c, 0x4d, 0x5c, 0x00, 0x74, 0x00, 0xbd,
	0x45, 0x98, 0xd0, 0x28, 0xc8, 0x98, 0xa4, 0x49, 0x70, 0x99, 0xf0, 0xe9, 0x37, 0xd7, 0xd4, 0x15,
	0x5b, 0xfa, 0xe1, 0x42, 0xf1, 0xef, 0x14, 0x8d, 0x10, 0x98, 0x51, 0x28, 0x43, 0x77, 0x63, 0x60,
	0x0c, 0x1d, 0xac, 0x7f, 0xab, 0xa9, 0x8b, 0x30, 0xc9, 0x88, 0x6b, 0x69, 0xb2, 0x00, 0xe8, 0x31,
	0x34, 0xa7, 0x71, 0x48, 0x59, 0x40, 0x23, 0xd7, 0x1e, 0x18, 0xc3, 0x0e, 0xb6, 0x35, 0x3e, 0x8d,
	0x90, 0x0b, 0xf6, 0x82, 0xa4, 0x82, 0x72, 0xe6, 0x36, 0x8b, 0x97, 0x12, 0x7a, 0x3f, 0x0d, 0x78,
	0x74, 0xc1, 0x16, 0x24, 0xa5, 0x5f, 0x29, 0x89, 0xaa, 0x07, 0xfa, 0xd0, 0x96, 0x77, 0x50, 0x5f,
	0xda, 0x1e, 0x39, 0x7e, 0xa5, 0x04, 0x57, 0x0b, 0xd0, 0x13, 0x68, 0x09, 0x3a, 0x63, 0xa1, 0xcc,
	0xd2, 0xc2, 0x04, 0x07, 0xdf, 0x11, 0x68, 0x1f, 0xac, 0x69, 0x7a, 0x73, 0x25, 0xb9, 0x76, 0x62,
	0x73, 0x64, 0xfb, 0x63, 0x0d, 0x71, 0x49, 0x7b, 0xbf, 0x0c, 0xe8, 0x4d, 0xe8, 0x8c, 0x2d, 0x8b,
	0x38, 0x81, 0xed, 0xca, 0x8e, 0xe0, 0x3b, 0x95, 0x71, 0x20, 0xe8, 0xac, 0x54, 0xb3, 0xe3, 0xff,
	0x53, 0x3a, 0x46, 0x95, 0x9e, 0x2f, 0x54, 0xc6, 0x13, 0x3a, 0x43, 0xbb, 0x60, 0xcb, 0x3c, 0x88,
	0x43, 0x11, 0x97, 0xe2, 0x2c, 0x99, 0x9f, 0x84, 0x22, 0x46, 0x3b, 0x60, 0x29, 0x99, 0x24, 0xd5,
	0xca, 0x1c, 0x5c, 0x22, 0xef, 0x2d, 0x74, 0x0f, 0xa3, 0xa8, 0x5c, 0x70, 0x73, 0x9e, 0x63, 0x72,
	0x8d, 0x0e, 0xc0, 0xcc, 0x98, 0xcc, 0x1f, 0x58, 0xaf, 0x6b, 0xbc, 0x17, 0x6b, 0xfd, 0xa2, 0x2a,
	0xc2, 0xa8, 0x8a, 0xf0, 0x5e, 0x42, 0xef, 0x73, 0x59, 0xa7, 0x30, 0x11, 0x6a, 0xdb, 0x1e, 0xb4,
	0xca, 0x6a, 0x22, 0x5c, 0x63, 0xd0, 0x18, 0x3a, 0xb8, 0x29, 0xcb, 0x77, 0xef, 0x13, 0x74, 0x8f,
	0x89, 0x3c, 0xcf, 0xdf, 0xa7, 0x7c, 0x7e, 0xc6, 0x79, 0xa2, 0x1a, 0xf6, 0xa1, 0xad, 0x03, 0x16,
	0x24, 0x74, 0x4e, 0xa5, 0x5e, 0x61, 0x62, 0xd0, 0xd4, 0x07, 0xc5, 0xa8, 0x88, 0xc8, 0x3c, 0x98,
	0xf2, 0x8c, 0x49, 0xed, 0x42, 0x07, 0xdb, 0x32, 0x1f, 0x2b, 0xe8, 0xc5, 0xd0, 0x3b, 0x62, 0x22,
	0x4b, 0x49, 0x75, 0xe0, 0x2e, 0xd8, 0x8c, 0x47, 0x44, 0x25, 0xca, 0xd0, 0xe5, 0x96, 0x82, 0xa7,
	0x11, 0x7a, 0x0a, 0xc5, 0xd8, 0x20, 0x13, 0x24, 0xd2, 0xa3, 0x4c, 0xdc, 0xd2, 0xcc, 0x85, 0x20,
	0xd1, 0xb2, 0xf2, 0xc6, 0x83, 0xca, 0xc5, 0xbd, 0xa7, 0x3e, 0xb0, 0xcc, 0x7b, 0x0e, 0xce, 0x38,
	0x21, 0x61, 0x7a, 0x2b, 0x7a, 0x07, 0xac, 0x98, 0xd0, 0x59, 0x7c, 0x6b, 0x40, 0x89, 0xbc, 0x63,
	0xd8, 0x2a, 0x2e, 0xbc, 0x73, 0xf8, 0xbf, 0xf7, 0x2d, 0xe9, 0xa9, 0xaf, 0x1c, 0xe0, 0xaf, 0x0e,
	0xba, 0x5f, 0xff, 0xc1, 0x1e, 0x58, 0x45, 0xd8, 0x51, 0x13, 0xcc, 0xc9, 0xd1, 0xf8, 0xac, 0x5b,
	0x43, 0x36, 0x34, 0x26, 0x1f, 0x47, 0x5d, 0x63, 0xf4, 0xa3, 0x0e, 0xe6, 0x61, 0x26, 0x63, 0xf4,
	0x06, 0x3a, 0x4b, 0x79, 0x41, 0x3d, 0x7f, 0x35, 0x7f, 0xfd, 0x35, 0x4a, 0x78, 0x35, 0xd5, 0xb8,
	0xe4, 0x27, 0xea, 0xf9, 0xab, 0xc9, 0xe8, 0xaf, 0x51, 0xaa, 0xd1, 0x87, 0xcd, 0xe5, 0xbf, 0x1c,
	0x21, 0x7f, 0x2d, 0x03, 0x7d, 0xcb, 0x3f, 0x9a, 0x5f, 0xc9, 0x1b, 0xaf, 0x86, 0x9e, 0x41, 0xeb,
	0xaf, 0xd1, 0xa8, 0xe3, 0x57, 0x4d, 0xaf, 0x54, 0xbd, 0x06, 0xa7, 0xea, 0x0e, 0xea, 0xfa, 0x2b,
	0xae, 0xf7, 0x57, 0x19, 0xe1, 0xd5, 0x2e, 0x2d, 0xfd, 0x95, 0x7d, 0xf5, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x26, 0x42, 0xe6, 0x19, 0x81, 0x05, 0x00, 0x00,
}
