// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Crypto int32

const (
	Crypto_SECP Crypto = 0
	Crypto_SM2  Crypto = 1
)

var Crypto_name = map[int32]string{
	0: "SECP",
	1: "SM2",
}
var Crypto_value = map[string]int32{
	"SECP": 0,
	"SM2":  1,
}

func (x Crypto) String() string {
	return proto.EnumName(Crypto_name, int32(x))
}
func (Crypto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{0}
}

type Transaction struct {
	To                   string   `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	Quota                uint64   `protobuf:"varint,3,opt,name=quota" json:"quota,omitempty"`
	ValidUntilBlock      uint64   `protobuf:"varint,4,opt,name=valid_until_block,json=validUntilBlock" json:"valid_until_block,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Value                []byte   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	ChainId              uint32   `protobuf:"varint,7,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Version              uint32   `protobuf:"varint,8,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetQuota() uint64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *Transaction) GetValidUntilBlock() uint64 {
	if m != nil {
		return m.ValidUntilBlock
	}
	return 0
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type UnverifiedTransaction struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
	Signature            []byte       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Crypto               Crypto       `protobuf:"varint,3,opt,name=crypto,enum=Crypto" json:"crypto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UnverifiedTransaction) Reset()         { *m = UnverifiedTransaction{} }
func (m *UnverifiedTransaction) String() string { return proto.CompactTextString(m) }
func (*UnverifiedTransaction) ProtoMessage()    {}
func (*UnverifiedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{1}
}
func (m *UnverifiedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnverifiedTransaction.Unmarshal(m, b)
}
func (m *UnverifiedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnverifiedTransaction.Marshal(b, m, deterministic)
}
func (dst *UnverifiedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnverifiedTransaction.Merge(dst, src)
}
func (m *UnverifiedTransaction) XXX_Size() int {
	return xxx_messageInfo_UnverifiedTransaction.Size(m)
}
func (m *UnverifiedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_UnverifiedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_UnverifiedTransaction proto.InternalMessageInfo

func (m *UnverifiedTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *UnverifiedTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *UnverifiedTransaction) GetCrypto() Crypto {
	if m != nil {
		return m.Crypto
	}
	return Crypto_SECP
}

type SignedTransaction struct {
	TransactionWithSig   *UnverifiedTransaction `protobuf:"bytes,1,opt,name=transaction_with_sig,json=transactionWithSig" json:"transaction_with_sig,omitempty"`
	TxHash               []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Signer               []byte                 `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SignedTransaction) Reset()         { *m = SignedTransaction{} }
func (m *SignedTransaction) String() string { return proto.CompactTextString(m) }
func (*SignedTransaction) ProtoMessage()    {}
func (*SignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{2}
}
func (m *SignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedTransaction.Unmarshal(m, b)
}
func (m *SignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedTransaction.Marshal(b, m, deterministic)
}
func (dst *SignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedTransaction.Merge(dst, src)
}
func (m *SignedTransaction) XXX_Size() int {
	return xxx_messageInfo_SignedTransaction.Size(m)
}
func (m *SignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SignedTransaction proto.InternalMessageInfo

func (m *SignedTransaction) GetTransactionWithSig() *UnverifiedTransaction {
	if m != nil {
		return m.TransactionWithSig
	}
	return nil
}

func (m *SignedTransaction) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *SignedTransaction) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

type AddUnverifyTxReq struct {
	Untx                 *UnverifiedTransaction `protobuf:"bytes,1,opt,name=untx" json:"untx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AddUnverifyTxReq) Reset()         { *m = AddUnverifyTxReq{} }
func (m *AddUnverifyTxReq) String() string { return proto.CompactTextString(m) }
func (*AddUnverifyTxReq) ProtoMessage()    {}
func (*AddUnverifyTxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{3}
}
func (m *AddUnverifyTxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUnverifyTxReq.Unmarshal(m, b)
}
func (m *AddUnverifyTxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUnverifyTxReq.Marshal(b, m, deterministic)
}
func (dst *AddUnverifyTxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUnverifyTxReq.Merge(dst, src)
}
func (m *AddUnverifyTxReq) XXX_Size() int {
	return xxx_messageInfo_AddUnverifyTxReq.Size(m)
}
func (m *AddUnverifyTxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUnverifyTxReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUnverifyTxReq proto.InternalMessageInfo

func (m *AddUnverifyTxReq) GetUntx() *UnverifiedTransaction {
	if m != nil {
		return m.Untx
	}
	return nil
}

type AddUnverifyTxRes struct {
	TxHash               []byte   `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUnverifyTxRes) Reset()         { *m = AddUnverifyTxRes{} }
func (m *AddUnverifyTxRes) String() string { return proto.CompactTextString(m) }
func (*AddUnverifyTxRes) ProtoMessage()    {}
func (*AddUnverifyTxRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{4}
}
func (m *AddUnverifyTxRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUnverifyTxRes.Unmarshal(m, b)
}
func (m *AddUnverifyTxRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUnverifyTxRes.Marshal(b, m, deterministic)
}
func (dst *AddUnverifyTxRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUnverifyTxRes.Merge(dst, src)
}
func (m *AddUnverifyTxRes) XXX_Size() int {
	return xxx_messageInfo_AddUnverifyTxRes.Size(m)
}
func (m *AddUnverifyTxRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUnverifyTxRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddUnverifyTxRes proto.InternalMessageInfo

func (m *AddUnverifyTxRes) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

type VerifyTxHashesReq struct {
	TxHashes             [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTxHashesReq) Reset()         { *m = VerifyTxHashesReq{} }
func (m *VerifyTxHashesReq) String() string { return proto.CompactTextString(m) }
func (*VerifyTxHashesReq) ProtoMessage()    {}
func (*VerifyTxHashesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{5}
}
func (m *VerifyTxHashesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTxHashesReq.Unmarshal(m, b)
}
func (m *VerifyTxHashesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTxHashesReq.Marshal(b, m, deterministic)
}
func (dst *VerifyTxHashesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTxHashesReq.Merge(dst, src)
}
func (m *VerifyTxHashesReq) XXX_Size() int {
	return xxx_messageInfo_VerifyTxHashesReq.Size(m)
}
func (m *VerifyTxHashesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTxHashesReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTxHashesReq proto.InternalMessageInfo

func (m *VerifyTxHashesReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

type GetTxFromPoolReq struct {
	QuotaLimit           uint64   `protobuf:"varint,1,opt,name=quota_limit,json=quotaLimit" json:"quota_limit,omitempty"`
	TxCount              uint32   `protobuf:"varint,2,opt,name=tx_count,json=txCount" json:"tx_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxFromPoolReq) Reset()         { *m = GetTxFromPoolReq{} }
func (m *GetTxFromPoolReq) String() string { return proto.CompactTextString(m) }
func (*GetTxFromPoolReq) ProtoMessage()    {}
func (*GetTxFromPoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{6}
}
func (m *GetTxFromPoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxFromPoolReq.Unmarshal(m, b)
}
func (m *GetTxFromPoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxFromPoolReq.Marshal(b, m, deterministic)
}
func (dst *GetTxFromPoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxFromPoolReq.Merge(dst, src)
}
func (m *GetTxFromPoolReq) XXX_Size() int {
	return xxx_messageInfo_GetTxFromPoolReq.Size(m)
}
func (m *GetTxFromPoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxFromPoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxFromPoolReq proto.InternalMessageInfo

func (m *GetTxFromPoolReq) GetQuotaLimit() uint64 {
	if m != nil {
		return m.QuotaLimit
	}
	return 0
}

func (m *GetTxFromPoolReq) GetTxCount() uint32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

type EnsureFromPoolReq struct {
	NodeAddress          []byte   `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	QuotaUsed            uint64   `protobuf:"varint,2,opt,name=quota_used,json=quotaUsed" json:"quota_used,omitempty"`
	TxHashes             [][]byte `protobuf:"bytes,3,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnsureFromPoolReq) Reset()         { *m = EnsureFromPoolReq{} }
func (m *EnsureFromPoolReq) String() string { return proto.CompactTextString(m) }
func (*EnsureFromPoolReq) ProtoMessage()    {}
func (*EnsureFromPoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{7}
}
func (m *EnsureFromPoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnsureFromPoolReq.Unmarshal(m, b)
}
func (m *EnsureFromPoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnsureFromPoolReq.Marshal(b, m, deterministic)
}
func (dst *EnsureFromPoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnsureFromPoolReq.Merge(dst, src)
}
func (m *EnsureFromPoolReq) XXX_Size() int {
	return xxx_messageInfo_EnsureFromPoolReq.Size(m)
}
func (m *EnsureFromPoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnsureFromPoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnsureFromPoolReq proto.InternalMessageInfo

func (m *EnsureFromPoolReq) GetNodeAddress() []byte {
	if m != nil {
		return m.NodeAddress
	}
	return nil
}

func (m *EnsureFromPoolReq) GetQuotaUsed() uint64 {
	if m != nil {
		return m.QuotaUsed
	}
	return 0
}

func (m *EnsureFromPoolReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

type GetTxFromPoolRes struct {
	TxHashes             [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	QuotaUsed            uint64   `protobuf:"varint,2,opt,name=quota_used,json=quotaUsed" json:"quota_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxFromPoolRes) Reset()         { *m = GetTxFromPoolRes{} }
func (m *GetTxFromPoolRes) String() string { return proto.CompactTextString(m) }
func (*GetTxFromPoolRes) ProtoMessage()    {}
func (*GetTxFromPoolRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{8}
}
func (m *GetTxFromPoolRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxFromPoolRes.Unmarshal(m, b)
}
func (m *GetTxFromPoolRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxFromPoolRes.Marshal(b, m, deterministic)
}
func (dst *GetTxFromPoolRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxFromPoolRes.Merge(dst, src)
}
func (m *GetTxFromPoolRes) XXX_Size() int {
	return xxx_messageInfo_GetTxFromPoolRes.Size(m)
}
func (m *GetTxFromPoolRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxFromPoolRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxFromPoolRes proto.InternalMessageInfo

func (m *GetTxFromPoolRes) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *GetTxFromPoolRes) GetQuotaUsed() uint64 {
	if m != nil {
		return m.QuotaUsed
	}
	return 0
}

type FlushPoolReq struct {
	TxHashes             [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlushPoolReq) Reset()         { *m = FlushPoolReq{} }
func (m *FlushPoolReq) String() string { return proto.CompactTextString(m) }
func (*FlushPoolReq) ProtoMessage()    {}
func (*FlushPoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{9}
}
func (m *FlushPoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlushPoolReq.Unmarshal(m, b)
}
func (m *FlushPoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlushPoolReq.Marshal(b, m, deterministic)
}
func (dst *FlushPoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlushPoolReq.Merge(dst, src)
}
func (m *FlushPoolReq) XXX_Size() int {
	return xxx_messageInfo_FlushPoolReq.Size(m)
}
func (m *FlushPoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FlushPoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_FlushPoolReq proto.InternalMessageInfo

func (m *FlushPoolReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

type GetUnverifyTxsReq struct {
	Node                 []byte   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	TxHashes             [][]byte `protobuf:"bytes,2,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUnverifyTxsReq) Reset()         { *m = GetUnverifyTxsReq{} }
func (m *GetUnverifyTxsReq) String() string { return proto.CompactTextString(m) }
func (*GetUnverifyTxsReq) ProtoMessage()    {}
func (*GetUnverifyTxsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{10}
}
func (m *GetUnverifyTxsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnverifyTxsReq.Unmarshal(m, b)
}
func (m *GetUnverifyTxsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnverifyTxsReq.Marshal(b, m, deterministic)
}
func (dst *GetUnverifyTxsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnverifyTxsReq.Merge(dst, src)
}
func (m *GetUnverifyTxsReq) XXX_Size() int {
	return xxx_messageInfo_GetUnverifyTxsReq.Size(m)
}
func (m *GetUnverifyTxsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnverifyTxsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnverifyTxsReq proto.InternalMessageInfo

func (m *GetUnverifyTxsReq) GetNode() []byte {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *GetUnverifyTxsReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

type GetUnverifyTxsRes struct {
	Untxs                []*UnverifiedTransaction `protobuf:"bytes,1,rep,name=untxs" json:"untxs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetUnverifyTxsRes) Reset()         { *m = GetUnverifyTxsRes{} }
func (m *GetUnverifyTxsRes) String() string { return proto.CompactTextString(m) }
func (*GetUnverifyTxsRes) ProtoMessage()    {}
func (*GetUnverifyTxsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3cb28289540142af, []int{11}
}
func (m *GetUnverifyTxsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnverifyTxsRes.Unmarshal(m, b)
}
func (m *GetUnverifyTxsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnverifyTxsRes.Marshal(b, m, deterministic)
}
func (dst *GetUnverifyTxsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnverifyTxsRes.Merge(dst, src)
}
func (m *GetUnverifyTxsRes) XXX_Size() int {
	return xxx_messageInfo_GetUnverifyTxsRes.Size(m)
}
func (m *GetUnverifyTxsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnverifyTxsRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnverifyTxsRes proto.InternalMessageInfo

func (m *GetUnverifyTxsRes) GetUntxs() []*UnverifiedTransaction {
	if m != nil {
		return m.Untxs
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*UnverifiedTransaction)(nil), "UnverifiedTransaction")
	proto.RegisterType((*SignedTransaction)(nil), "SignedTransaction")
	proto.RegisterType((*AddUnverifyTxReq)(nil), "AddUnverifyTxReq")
	proto.RegisterType((*AddUnverifyTxRes)(nil), "AddUnverifyTxRes")
	proto.RegisterType((*VerifyTxHashesReq)(nil), "VerifyTxHashesReq")
	proto.RegisterType((*GetTxFromPoolReq)(nil), "GetTxFromPoolReq")
	proto.RegisterType((*EnsureFromPoolReq)(nil), "EnsureFromPoolReq")
	proto.RegisterType((*GetTxFromPoolRes)(nil), "GetTxFromPoolRes")
	proto.RegisterType((*FlushPoolReq)(nil), "FlushPoolReq")
	proto.RegisterType((*GetUnverifyTxsReq)(nil), "GetUnverifyTxsReq")
	proto.RegisterType((*GetUnverifyTxsRes)(nil), "GetUnverifyTxsRes")
	proto.RegisterEnum("Crypto", Crypto_name, Crypto_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	AddUnverifyTx(ctx context.Context, in *AddUnverifyTxReq, opts ...grpc.CallOption) (*AddUnverifyTxRes, error)
	GetTxFromPool(ctx context.Context, in *GetTxFromPoolReq, opts ...grpc.CallOption) (*GetTxFromPoolRes, error)
	EnsureFromPool(ctx context.Context, in *EnsureFromPoolReq, opts ...grpc.CallOption) (*Empty, error)
	FlushPool(ctx context.Context, in *FlushPoolReq, opts ...grpc.CallOption) (*Empty, error)
	GetUnverifyTxs(ctx context.Context, in *GetUnverifyTxsReq, opts ...grpc.CallOption) (*GetUnverifyTxsRes, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AddUnverifyTx(ctx context.Context, in *AddUnverifyTxReq, opts ...grpc.CallOption) (*AddUnverifyTxRes, error) {
	out := new(AddUnverifyTxRes)
	err := c.cc.Invoke(ctx, "/Auth/AddUnverifyTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetTxFromPool(ctx context.Context, in *GetTxFromPoolReq, opts ...grpc.CallOption) (*GetTxFromPoolRes, error) {
	out := new(GetTxFromPoolRes)
	err := c.cc.Invoke(ctx, "/Auth/GetTxFromPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) EnsureFromPool(ctx context.Context, in *EnsureFromPoolReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Auth/EnsureFromPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) FlushPool(ctx context.Context, in *FlushPoolReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Auth/FlushPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetUnverifyTxs(ctx context.Context, in *GetUnverifyTxsReq, opts ...grpc.CallOption) (*GetUnverifyTxsRes, error) {
	out := new(GetUnverifyTxsRes)
	err := c.cc.Invoke(ctx, "/Auth/GetUnverifyTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	AddUnverifyTx(context.Context, *AddUnverifyTxReq) (*AddUnverifyTxRes, error)
	GetTxFromPool(context.Context, *GetTxFromPoolReq) (*GetTxFromPoolRes, error)
	EnsureFromPool(context.Context, *EnsureFromPoolReq) (*Empty, error)
	FlushPool(context.Context, *FlushPoolReq) (*Empty, error)
	GetUnverifyTxs(context.Context, *GetUnverifyTxsReq) (*GetUnverifyTxsRes, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_AddUnverifyTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUnverifyTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AddUnverifyTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/AddUnverifyTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AddUnverifyTx(ctx, req.(*AddUnverifyTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetTxFromPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxFromPoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetTxFromPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/GetTxFromPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetTxFromPool(ctx, req.(*GetTxFromPoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_EnsureFromPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureFromPoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).EnsureFromPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/EnsureFromPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).EnsureFromPool(ctx, req.(*EnsureFromPoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_FlushPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushPoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).FlushPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/FlushPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).FlushPool(ctx, req.(*FlushPoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetUnverifyTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnverifyTxsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetUnverifyTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/GetUnverifyTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetUnverifyTxs(ctx, req.(*GetUnverifyTxsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUnverifyTx",
			Handler:    _Auth_AddUnverifyTx_Handler,
		},
		{
			MethodName: "GetTxFromPool",
			Handler:    _Auth_GetTxFromPool_Handler,
		},
		{
			MethodName: "EnsureFromPool",
			Handler:    _Auth_EnsureFromPool_Handler,
		},
		{
			MethodName: "FlushPool",
			Handler:    _Auth_FlushPool_Handler,
		},
		{
			MethodName: "GetUnverifyTxs",
			Handler:    _Auth_GetUnverifyTxs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_3cb28289540142af) }

var fileDescriptor_auth_3cb28289540142af = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0xda, 0xac, 0x1f, 0xb7, 0x69, 0x69, 0xad, 0x31, 0x42, 0x07, 0x5a, 0x89, 0x78, 0xa8,
	0x36, 0x14, 0xa1, 0xf2, 0x80, 0xc4, 0x03, 0x52, 0x19, 0xfb, 0x40, 0x02, 0x34, 0xb9, 0x1b, 0x3c,
	0x46, 0x59, 0x63, 0x1a, 0x8b, 0xd4, 0xde, 0x62, 0xa7, 0x64, 0x7f, 0x80, 0x07, 0x1e, 0xf8, 0x75,
	0xfc, 0x20, 0x64, 0x27, 0xb0, 0x64, 0x81, 0xed, 0xcd, 0xe7, 0xf8, 0x7e, 0x9c, 0x7b, 0x7d, 0x12,
	0x00, 0x3f, 0x91, 0xa1, 0x7b, 0x11, 0x73, 0xc9, 0x47, 0xd6, 0x82, 0xaf, 0x56, 0x9c, 0x65, 0xc8,
	0xf9, 0x65, 0x40, 0xf7, 0x34, 0xf6, 0x99, 0xf0, 0x17, 0x92, 0x72, 0x86, 0xfa, 0x50, 0x97, 0xdc,
	0x36, 0xc6, 0xc6, 0xa4, 0x83, 0xeb, 0x92, 0xa3, 0x4d, 0xd8, 0x60, 0x9c, 0x2d, 0x88, 0x5d, 0xd7,
	0x54, 0x06, 0x14, 0x7b, 0x99, 0x70, 0xe9, 0xdb, 0x8d, 0xb1, 0x31, 0x31, 0x71, 0x06, 0xd0, 0x2e,
	0x0c, 0xd7, 0x7e, 0x44, 0x03, 0x2f, 0x61, 0x92, 0x46, 0xde, 0x79, 0xc4, 0x17, 0x5f, 0x6d, 0x53,
	0x47, 0xdc, 0xd3, 0x17, 0x67, 0x8a, 0x7f, 0xa3, 0x68, 0x84, 0xc0, 0x0c, 0x7c, 0xe9, 0xdb, 0x1b,
	0x63, 0x63, 0x62, 0x61, 0x7d, 0x56, 0x55, 0xd7, 0x7e, 0x94, 0x10, 0xbb, 0xa9, 0xc9, 0x0c, 0xa0,
	0x87, 0xd0, 0x5e, 0x84, 0x3e, 0x65, 0x1e, 0x0d, 0xec, 0xd6, 0xd8, 0x98, 0xf4, 0x70, 0x4b, 0xe3,
	0x77, 0x01, 0xb2, 0xa1, 0xb5, 0x26, 0xb1, 0xa0, 0x9c, 0xd9, 0xed, 0xec, 0x26, 0x87, 0xce, 0x77,
	0x03, 0xee, 0x9f, 0xb1, 0x35, 0x89, 0xe9, 0x17, 0x4a, 0x82, 0xe2, 0x80, 0x2e, 0x74, 0xe5, 0x35,
	0xd4, 0x93, 0x76, 0xa7, 0x96, 0x5b, 0x08, 0xc1, 0xc5, 0x00, 0xf4, 0x08, 0x3a, 0x82, 0x2e, 0x99,
	0x2f, 0x93, 0x38, 0x5b, 0x82, 0x85, 0xaf, 0x09, 0xb4, 0x03, 0xcd, 0x45, 0x7c, 0x75, 0x21, 0xb9,
	0xde, 0x44, 0x7f, 0xda, 0x72, 0xf7, 0x35, 0xc4, 0x39, 0xed, 0xfc, 0x34, 0x60, 0x38, 0xa7, 0x4b,
	0x56, 0x16, 0x71, 0x0c, 0x9b, 0x85, 0x1e, 0xde, 0x37, 0x2a, 0x43, 0x4f, 0xd0, 0x65, 0xae, 0x66,
	0xcb, 0xfd, 0xa7, 0x74, 0x8c, 0x0a, 0x39, 0x9f, 0xa9, 0x0c, 0xe7, 0x74, 0x89, 0x1e, 0x40, 0x4b,
	0xa6, 0x5e, 0xe8, 0x8b, 0x30, 0x17, 0xd7, 0x94, 0xe9, 0xb1, 0x2f, 0x42, 0xb4, 0x05, 0x4d, 0x25,
	0x93, 0xc4, 0x5a, 0x99, 0x85, 0x73, 0xe4, 0xbc, 0x86, 0xc1, 0x2c, 0x08, 0xf2, 0x06, 0x57, 0xa7,
	0x29, 0x26, 0x97, 0x68, 0x17, 0xcc, 0x84, 0xc9, 0xf4, 0x8e, 0xf6, 0x3a, 0xc6, 0xd9, 0xab, 0xe4,
	0x8b, 0xa2, 0x08, 0xa3, 0x28, 0xc2, 0x79, 0x0e, 0xc3, 0x4f, 0x79, 0x9c, 0xc2, 0x44, 0xa8, 0x6e,
	0xdb, 0xd0, 0xc9, 0xa3, 0x89, 0xb0, 0x8d, 0x71, 0x63, 0x62, 0xe1, 0xb6, 0xcc, 0xef, 0x9d, 0x8f,
	0x30, 0x38, 0x22, 0xf2, 0x34, 0x3d, 0x8c, 0xf9, 0xea, 0x84, 0xf3, 0x48, 0x25, 0xec, 0x40, 0x57,
	0x1b, 0xcc, 0x8b, 0xe8, 0x8a, 0x4a, 0xdd, 0xc2, 0xc4, 0xa0, 0xa9, 0xf7, 0x8a, 0x51, 0x16, 0x91,
	0xa9, 0xb7, 0xe0, 0x09, 0x93, 0x7a, 0x0b, 0x3d, 0xdc, 0x92, 0xe9, 0xbe, 0x82, 0x4e, 0x0c, 0xc3,
	0x03, 0x26, 0x92, 0x98, 0x14, 0x0b, 0x3e, 0x01, 0x8b, 0xf1, 0x80, 0x78, 0x7e, 0x10, 0xc4, 0x44,
	0x88, 0x5c, 0x74, 0x57, 0x71, 0xb3, 0x8c, 0x42, 0x8f, 0x21, 0x6b, 0xe0, 0x25, 0x82, 0x04, 0xba,
	0xa8, 0x89, 0x3b, 0x9a, 0x39, 0x13, 0x24, 0x28, 0xcf, 0xd0, 0xb8, 0x73, 0x06, 0x71, 0xeb, 0xd0,
	0x77, 0x34, 0x73, 0xf6, 0xc0, 0x3a, 0x8c, 0x12, 0x11, 0xfe, 0x91, 0x7f, 0xeb, 0x02, 0xdf, 0xc2,
	0xf0, 0x88, 0xc8, 0xeb, 0xf7, 0xd1, 0x2b, 0x47, 0x60, 0xaa, 0xe1, 0xf2, 0x41, 0xf5, 0xb9, 0x5c,
	0xa5, 0x7e, 0xa3, 0xca, 0xac, 0x5a, 0x45, 0xa0, 0x67, 0xb0, 0xa1, 0x2c, 0x90, 0xf5, 0xfc, 0xbf,
	0x4f, 0xb2, 0xa0, 0xdd, 0x6d, 0x68, 0x66, 0xdf, 0x02, 0x6a, 0x83, 0x39, 0x3f, 0xd8, 0x3f, 0x19,
	0xd4, 0x50, 0x0b, 0x1a, 0xf3, 0x0f, 0xd3, 0x81, 0x31, 0xfd, 0x51, 0x07, 0x73, 0x96, 0xc8, 0x10,
	0xbd, 0x84, 0x5e, 0xc9, 0x4e, 0x68, 0xe8, 0xde, 0xb4, 0xe7, 0xa8, 0x42, 0x09, 0xa7, 0xa6, 0x12,
	0x4b, 0x4b, 0x46, 0x43, 0xf7, 0xa6, 0x71, 0x46, 0x15, 0x4a, 0x25, 0xba, 0xd0, 0x2f, 0x3b, 0x02,
	0x21, 0xb7, 0x62, 0x91, 0x51, 0xd3, 0x3d, 0x58, 0x5d, 0xc8, 0x2b, 0xa7, 0x86, 0x9e, 0x42, 0xe7,
	0xef, 0xf6, 0x51, 0xcf, 0x2d, 0xbe, 0x44, 0x21, 0xea, 0x15, 0xf4, 0xcb, 0x0b, 0x43, 0xc8, 0xad,
	0xbc, 0xc3, 0xa8, 0xca, 0x09, 0xa7, 0x76, 0xde, 0xd4, 0xbf, 0xe2, 0x17, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x49, 0x97, 0x05, 0x79, 0xa6, 0x05, 0x00, 0x00,
}
