// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BroadcastProposalReq struct {
	Proposal             *Proposal `protobuf:"bytes,1,opt,name=proposal" json:"proposal,omitempty"`
	Signature            []byte    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BroadcastProposalReq) Reset()         { *m = BroadcastProposalReq{} }
func (m *BroadcastProposalReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastProposalReq) ProtoMessage()    {}
func (*BroadcastProposalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_ceef2a8ee04932c1, []int{0}
}
func (m *BroadcastProposalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastProposalReq.Unmarshal(m, b)
}
func (m *BroadcastProposalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastProposalReq.Marshal(b, m, deterministic)
}
func (dst *BroadcastProposalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastProposalReq.Merge(dst, src)
}
func (m *BroadcastProposalReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastProposalReq.Size(m)
}
func (m *BroadcastProposalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastProposalReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastProposalReq proto.InternalMessageInfo

func (m *BroadcastProposalReq) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *BroadcastProposalReq) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BroadcastVotelReq struct {
	Vote                 *Vote    `protobuf:"bytes,1,opt,name=vote" json:"vote,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastVotelReq) Reset()         { *m = BroadcastVotelReq{} }
func (m *BroadcastVotelReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastVotelReq) ProtoMessage()    {}
func (*BroadcastVotelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_ceef2a8ee04932c1, []int{1}
}
func (m *BroadcastVotelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastVotelReq.Unmarshal(m, b)
}
func (m *BroadcastVotelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastVotelReq.Marshal(b, m, deterministic)
}
func (dst *BroadcastVotelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastVotelReq.Merge(dst, src)
}
func (m *BroadcastVotelReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastVotelReq.Size(m)
}
func (m *BroadcastVotelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastVotelReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastVotelReq proto.InternalMessageInfo

func (m *BroadcastVotelReq) GetVote() *Vote {
	if m != nil {
		return m.Vote
	}
	return nil
}

func (m *BroadcastVotelReq) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*BroadcastProposalReq)(nil), "BroadcastProposalReq")
	proto.RegisterType((*BroadcastVotelReq)(nil), "BroadcastVotelReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NetworkClient is the client API for Network service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkClient interface {
	BroadcastProposal(ctx context.Context, in *BroadcastProposalReq, opts ...grpc.CallOption) (*Empty, error)
	BroadcastVote(ctx context.Context, in *BroadcastVotelReq, opts ...grpc.CallOption) (*Empty, error)
}

type networkClient struct {
	cc *grpc.ClientConn
}

func NewNetworkClient(cc *grpc.ClientConn) NetworkClient {
	return &networkClient{cc}
}

func (c *networkClient) BroadcastProposal(ctx context.Context, in *BroadcastProposalReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Network/BroadcastProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) BroadcastVote(ctx context.Context, in *BroadcastVotelReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Network/BroadcastVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServer is the server API for Network service.
type NetworkServer interface {
	BroadcastProposal(context.Context, *BroadcastProposalReq) (*Empty, error)
	BroadcastVote(context.Context, *BroadcastVotelReq) (*Empty, error)
}

func RegisterNetworkServer(s *grpc.Server, srv NetworkServer) {
	s.RegisterService(&_Network_serviceDesc, srv)
}

func _Network_BroadcastProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastProposalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).BroadcastProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Network/BroadcastProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).BroadcastProposal(ctx, req.(*BroadcastProposalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_BroadcastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastVotelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).BroadcastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Network/BroadcastVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).BroadcastVote(ctx, req.(*BroadcastVotelReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Network_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Network",
	HandlerType: (*NetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastProposal",
			Handler:    _Network_BroadcastProposal_Handler,
		},
		{
			MethodName: "BroadcastVote",
			Handler:    _Network_BroadcastVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network.proto",
}

func init() { proto.RegisterFile("network.proto", fileDescriptor_network_ceef2a8ee04932c1) }

var fileDescriptor_network_ceef2a8ee04932c1 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4b, 0x2d, 0x29,
	0xcf, 0x2f, 0xca, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x4f, 0xce, 0xcf, 0x2b, 0x4e,
	0xcd, 0x2b, 0x2e, 0x2d, 0x86, 0x0a, 0xf0, 0x24, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0x41, 0x78, 0x4a,
	0xd1, 0x5c, 0x22, 0x4e, 0x45, 0xf9, 0x89, 0x29, 0xc9, 0x89, 0xc5, 0x25, 0x01, 0x45, 0xf9, 0x05,
	0xf9, 0xc5, 0x89, 0x39, 0x41, 0xa9, 0x85, 0x42, 0xaa, 0x5c, 0x1c, 0x05, 0x50, 0xae, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0xb7, 0x11, 0xa7, 0x1e, 0x5c, 0x1e, 0x2e, 0x25, 0x24, 0xc3, 0xc5, 0x59, 0x9c,
	0x99, 0x9e, 0x97, 0x58, 0x52, 0x5a, 0x94, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13, 0x84, 0x10,
	0x50, 0xf2, 0xe1, 0x12, 0x84, 0x1b, 0x1e, 0x96, 0x5f, 0x92, 0x0a, 0x36, 0x59, 0x92, 0x8b, 0xa5,
	0x2c, 0xbf, 0x24, 0x15, 0x6a, 0x2a, 0xab, 0x1e, 0x48, 0x22, 0x08, 0x2c, 0x84, 0xdf, 0x34, 0xa3,
	0x3c, 0x2e, 0x76, 0x3f, 0x88, 0xd7, 0x84, 0x4c, 0x90, 0x0c, 0x86, 0xb9, 0x4a, 0x48, 0x54, 0x0f,
	0x9b, 0x4f, 0xa4, 0xd8, 0xf4, 0x5c, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0x18, 0x84, 0x74, 0xb9, 0x78,
	0x51, 0x9c, 0x23, 0x24, 0xa4, 0x87, 0xe1, 0x3c, 0x84, 0xf2, 0x24, 0x36, 0x70, 0x08, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x22, 0x4b, 0xe1, 0x8e, 0x51, 0x01, 0x00, 0x00,
}
