// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vm.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallReq struct {
	TxHashes             [][]byte     `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	Header               *BlockHeader `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CallReq) Reset()         { *m = CallReq{} }
func (m *CallReq) String() string { return proto.CompactTextString(m) }
func (*CallReq) ProtoMessage()    {}
func (*CallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_29b200c8878682ac, []int{0}
}
func (m *CallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallReq.Unmarshal(m, b)
}
func (m *CallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallReq.Marshal(b, m, deterministic)
}
func (dst *CallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallReq.Merge(dst, src)
}
func (m *CallReq) XXX_Size() int {
	return xxx_messageInfo_CallReq.Size(m)
}
func (m *CallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallReq proto.InternalMessageInfo

func (m *CallReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *CallReq) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CallRes struct {
	Receipts             []*Receipt `protobuf:"bytes,1,rep,name=receipts" json:"receipts,omitempty"`
	StateRoot            []byte     `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CallRes) Reset()         { *m = CallRes{} }
func (m *CallRes) String() string { return proto.CompactTextString(m) }
func (*CallRes) ProtoMessage()    {}
func (*CallRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_29b200c8878682ac, []int{1}
}
func (m *CallRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRes.Unmarshal(m, b)
}
func (m *CallRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRes.Marshal(b, m, deterministic)
}
func (dst *CallRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRes.Merge(dst, src)
}
func (m *CallRes) XXX_Size() int {
	return xxx_messageInfo_CallRes.Size(m)
}
func (m *CallRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRes.DiscardUnknown(m)
}

var xxx_messageInfo_CallRes proto.InternalMessageInfo

func (m *CallRes) GetReceipts() []*Receipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func (m *CallRes) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

type StaticCallReq struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticCallReq) Reset()         { *m = StaticCallReq{} }
func (m *StaticCallReq) String() string { return proto.CompactTextString(m) }
func (*StaticCallReq) ProtoMessage()    {}
func (*StaticCallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_29b200c8878682ac, []int{2}
}
func (m *StaticCallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticCallReq.Unmarshal(m, b)
}
func (m *StaticCallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticCallReq.Marshal(b, m, deterministic)
}
func (dst *StaticCallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticCallReq.Merge(dst, src)
}
func (m *StaticCallReq) XXX_Size() int {
	return xxx_messageInfo_StaticCallReq.Size(m)
}
func (m *StaticCallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticCallReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticCallReq proto.InternalMessageInfo

func (m *StaticCallReq) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *StaticCallReq) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *StaticCallReq) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *StaticCallReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StaticCallRes struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticCallRes) Reset()         { *m = StaticCallRes{} }
func (m *StaticCallRes) String() string { return proto.CompactTextString(m) }
func (*StaticCallRes) ProtoMessage()    {}
func (*StaticCallRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_29b200c8878682ac, []int{3}
}
func (m *StaticCallRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticCallRes.Unmarshal(m, b)
}
func (m *StaticCallRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticCallRes.Marshal(b, m, deterministic)
}
func (dst *StaticCallRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticCallRes.Merge(dst, src)
}
func (m *StaticCallRes) XXX_Size() int {
	return xxx_messageInfo_StaticCallRes.Size(m)
}
func (m *StaticCallRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticCallRes.DiscardUnknown(m)
}

var xxx_messageInfo_StaticCallRes proto.InternalMessageInfo

func (m *StaticCallRes) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*CallReq)(nil), "CallReq")
	proto.RegisterType((*CallRes)(nil), "CallRes")
	proto.RegisterType((*StaticCallReq)(nil), "StaticCallReq")
	proto.RegisterType((*StaticCallRes)(nil), "StaticCallRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VMClient is the client API for VM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMClient interface {
	Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallRes, error)
	StaticCall(ctx context.Context, in *StaticCallReq, opts ...grpc.CallOption) (*StaticCallRes, error)
}

type vMClient struct {
	cc *grpc.ClientConn
}

func NewVMClient(cc *grpc.ClientConn) VMClient {
	return &vMClient{cc}
}

func (c *vMClient) Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallRes, error) {
	out := new(CallRes)
	err := c.cc.Invoke(ctx, "/VM/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMClient) StaticCall(ctx context.Context, in *StaticCallReq, opts ...grpc.CallOption) (*StaticCallRes, error) {
	out := new(StaticCallRes)
	err := c.cc.Invoke(ctx, "/VM/StaticCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMServer is the server API for VM service.
type VMServer interface {
	Call(context.Context, *CallReq) (*CallRes, error)
	StaticCall(context.Context, *StaticCallReq) (*StaticCallRes, error)
}

func RegisterVMServer(s *grpc.Server, srv VMServer) {
	s.RegisterService(&_VM_serviceDesc, srv)
}

func _VM_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VM/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).Call(ctx, req.(*CallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VM_StaticCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).StaticCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VM/StaticCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).StaticCall(ctx, req.(*StaticCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _VM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VM",
	HandlerType: (*VMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _VM_Call_Handler,
		},
		{
			MethodName: "StaticCall",
			Handler:    _VM_StaticCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}

func init() { proto.RegisterFile("vm.proto", fileDescriptor_vm_29b200c8878682ac) }

var fileDescriptor_vm_29b200c8878682ac = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xc1, 0x4e, 0x84, 0x30,
	0x14, 0x5c, 0x58, 0xb2, 0xb2, 0x0f, 0xdc, 0x43, 0x0f, 0x86, 0xa0, 0x26, 0xa4, 0x31, 0x91, 0x53,
	0x0f, 0xf8, 0x07, 0x7a, 0xd9, 0x83, 0x7a, 0xa8, 0x89, 0x57, 0x52, 0xd9, 0x2a, 0x44, 0xd6, 0xb7,
	0xb6, 0x4f, 0xb3, 0x9f, 0x6f, 0x5a, 0xc0, 0x0d, 0xb7, 0x99, 0x79, 0xd3, 0x99, 0x49, 0x0a, 0xf1,
	0xef, 0x5e, 0x1c, 0x0c, 0x12, 0xe6, 0x49, 0xd3, 0xaa, 0xee, 0x6b, 0x20, 0xfc, 0x11, 0xce, 0x1e,
	0x54, 0xdf, 0x4b, 0xfd, 0xcd, 0x2e, 0x61, 0x4d, 0xc7, 0xba, 0x55, 0xb6, 0xd5, 0x36, 0x0b, 0x8a,
	0x65, 0x99, 0xca, 0x98, 0x8e, 0x5b, 0xcf, 0xd9, 0x0d, 0xac, 0x5a, 0xad, 0x76, 0xda, 0x64, 0x61,
	0x11, 0x94, 0x49, 0x95, 0x8a, 0xfb, 0x1e, 0x9b, 0xcf, 0xad, 0xd7, 0xe4, 0x78, 0xe3, 0xcf, 0x53,
	0x9a, 0x7b, 0x10, 0x1b, 0xdd, 0xe8, 0xee, 0x40, 0x43, 0x58, 0x52, 0xc5, 0x42, 0x0e, 0x82, 0xfc,
	0xbf, 0xb0, 0x6b, 0x00, 0x4b, 0x8a, 0x74, 0x6d, 0x10, 0xc9, 0x47, 0xa7, 0x72, 0xed, 0x15, 0x89,
	0x48, 0xbc, 0x86, 0xf3, 0x17, 0x52, 0xd4, 0x35, 0xd3, 0xc6, 0x0b, 0x37, 0xa3, 0xfb, 0x68, 0x29,
	0x0b, 0x8a, 0xa0, 0x8c, 0xe4, 0xc8, 0x18, 0x83, 0xe8, 0xdd, 0xe0, 0x7e, 0x4c, 0xf0, 0x98, 0x6d,
	0x20, 0x24, 0xcc, 0x96, 0x5e, 0x09, 0x09, 0x9d, 0x67, 0xa7, 0x48, 0x65, 0xd1, 0xe0, 0x71, 0x98,
	0xdf, 0xce, 0x0b, 0xac, 0x2b, 0x30, 0xda, 0xfe, 0xf4, 0x43, 0x41, 0x2a, 0x47, 0x56, 0x49, 0x08,
	0x5f, 0x9f, 0xd8, 0x15, 0x44, 0xce, 0xc8, 0x62, 0x31, 0x0e, 0xca, 0x27, 0x64, 0xf9, 0x82, 0x09,
	0x80, 0x53, 0x18, 0xdb, 0x88, 0xd9, 0xf4, 0x7c, 0xce, 0x2d, 0x5f, 0xbc, 0xad, 0xfc, 0x17, 0xdc,
	0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x68, 0x3f, 0x9d, 0x9b, 0x01, 0x00, 0x00,
}
