// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vm.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Receipt struct {
	StateRoot            []byte      `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	GasUsed              uint64      `protobuf:"varint,2,opt,name=gas_used,json=gasUsed" json:"gas_used,omitempty"`
	LogBloom             []byte      `protobuf:"bytes,3,opt,name=log_bloom,json=logBloom,proto3" json:"log_bloom,omitempty"`
	Logs                 []*LogEntry `protobuf:"bytes,4,rep,name=logs" json:"logs,omitempty"`
	Error                string      `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
	TransactionHash      []byte      `protobuf:"bytes,7,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	ContractAddress      []byte      `protobuf:"bytes,8,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_7907c87f3cca95af, []int{0}
}
func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (dst *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(dst, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *Receipt) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *Receipt) GetLogBloom() []byte {
	if m != nil {
		return m.LogBloom
	}
	return nil
}

func (m *Receipt) GetLogs() []*LogEntry {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *Receipt) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Receipt) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *Receipt) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

type LogEntry struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics               [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_7907c87f3cca95af, []int{1}
}
func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (dst *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(dst, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LogEntry) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *LogEntry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CallReq struct {
	TxHashes             [][]byte     `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	Header               *BlockHeader `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CallReq) Reset()         { *m = CallReq{} }
func (m *CallReq) String() string { return proto.CompactTextString(m) }
func (*CallReq) ProtoMessage()    {}
func (*CallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_7907c87f3cca95af, []int{2}
}
func (m *CallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallReq.Unmarshal(m, b)
}
func (m *CallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallReq.Marshal(b, m, deterministic)
}
func (dst *CallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallReq.Merge(dst, src)
}
func (m *CallReq) XXX_Size() int {
	return xxx_messageInfo_CallReq.Size(m)
}
func (m *CallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallReq proto.InternalMessageInfo

func (m *CallReq) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *CallReq) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CallRes struct {
	Receipts             []*Receipt `protobuf:"bytes,1,rep,name=receipts" json:"receipts,omitempty"`
	StateRoot            []byte     `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CallRes) Reset()         { *m = CallRes{} }
func (m *CallRes) String() string { return proto.CompactTextString(m) }
func (*CallRes) ProtoMessage()    {}
func (*CallRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_7907c87f3cca95af, []int{3}
}
func (m *CallRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRes.Unmarshal(m, b)
}
func (m *CallRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRes.Marshal(b, m, deterministic)
}
func (dst *CallRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRes.Merge(dst, src)
}
func (m *CallRes) XXX_Size() int {
	return xxx_messageInfo_CallRes.Size(m)
}
func (m *CallRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRes.DiscardUnknown(m)
}

var xxx_messageInfo_CallRes proto.InternalMessageInfo

func (m *CallRes) GetReceipts() []*Receipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func (m *CallRes) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*Receipt)(nil), "Receipt")
	proto.RegisterType((*LogEntry)(nil), "LogEntry")
	proto.RegisterType((*CallReq)(nil), "CallReq")
	proto.RegisterType((*CallRes)(nil), "CallRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VMClient is the client API for VM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMClient interface {
	Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallRes, error)
}

type vMClient struct {
	cc *grpc.ClientConn
}

func NewVMClient(cc *grpc.ClientConn) VMClient {
	return &vMClient{cc}
}

func (c *vMClient) Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallRes, error) {
	out := new(CallRes)
	err := c.cc.Invoke(ctx, "/VM/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMServer is the server API for VM service.
type VMServer interface {
	Call(context.Context, *CallReq) (*CallRes, error)
}

func RegisterVMServer(s *grpc.Server, srv VMServer) {
	s.RegisterService(&_VM_serviceDesc, srv)
}

func _VM_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VM/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServer).Call(ctx, req.(*CallReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _VM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VM",
	HandlerType: (*VMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _VM_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}

func init() { proto.RegisterFile("vm.proto", fileDescriptor_vm_7907c87f3cca95af) }

var fileDescriptor_vm_7907c87f3cca95af = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xc1, 0x6a, 0xe3, 0x30,
	0x10, 0x5d, 0x3b, 0x4e, 0x2c, 0x8f, 0x03, 0xbb, 0x88, 0x65, 0xd1, 0x66, 0x37, 0x60, 0x4c, 0x0f,
	0xee, 0xc5, 0x07, 0xf7, 0x0b, 0x9a, 0x52, 0xc8, 0x21, 0x2d, 0x45, 0xd0, 0x5e, 0x8d, 0x62, 0x0b,
	0xdb, 0xd4, 0xf1, 0xa4, 0x92, 0x5a, 0xd2, 0x6f, 0xee, 0x4f, 0x14, 0xcb, 0x76, 0x29, 0xb9, 0xcd,
	0x7b, 0x33, 0xf3, 0x34, 0x33, 0x4f, 0x40, 0xde, 0x0e, 0xe9, 0x51, 0xa1, 0xc1, 0x55, 0x58, 0xd4,
	0xa2, 0xe9, 0x06, 0x10, 0x7f, 0x38, 0xe0, 0x73, 0x59, 0xc8, 0xe6, 0x68, 0xe8, 0x1a, 0x40, 0x1b,
	0x61, 0x64, 0xae, 0x10, 0x0d, 0x73, 0x22, 0x27, 0x59, 0xf2, 0xc0, 0x32, 0x1c, 0xd1, 0xd0, 0xbf,
	0x40, 0x2a, 0xa1, 0xf3, 0x57, 0x2d, 0x4b, 0xe6, 0x46, 0x4e, 0xe2, 0x71, 0xbf, 0x12, 0xfa, 0x51,
	0xcb, 0x92, 0xfe, 0x83, 0xa0, 0xc5, 0x2a, 0xdf, 0xb7, 0x88, 0x07, 0x36, 0xb3, 0x8d, 0xa4, 0xc5,
	0x6a, 0xd3, 0x63, 0xba, 0x06, 0xaf, 0xc5, 0x4a, 0x33, 0x2f, 0x9a, 0x25, 0x61, 0x16, 0xa4, 0x3b,
	0xac, 0x6e, 0x3b, 0xa3, 0xde, 0xb9, 0xa5, 0xe9, 0x6f, 0x98, 0x4b, 0xa5, 0x50, 0xb1, 0x79, 0xe4,
	0x24, 0x01, 0x1f, 0x00, 0xbd, 0x84, 0x5f, 0x46, 0x89, 0x4e, 0x8b, 0xc2, 0x34, 0xd8, 0xe5, 0xb5,
	0xd0, 0x35, 0xf3, 0xad, 0xf0, 0xcf, 0x6f, 0xfc, 0x56, 0xe8, 0xba, 0x2f, 0x2d, 0xb0, 0x33, 0x4a,
	0x14, 0x26, 0x17, 0x65, 0xa9, 0xa4, 0xd6, 0x8c, 0x0c, 0xa5, 0x13, 0x7f, 0x3d, 0xd0, 0xf1, 0x03,
	0x90, 0xe9, 0x75, 0xca, 0xc0, 0x9f, 0xaa, 0x87, 0x55, 0x27, 0x48, 0xff, 0xc0, 0xc2, 0xe0, 0xb1,
	0x29, 0x34, 0x73, 0xa3, 0x59, 0xb2, 0xe4, 0x23, 0xa2, 0x14, 0xbc, 0x52, 0x18, 0x31, 0x2e, 0x68,
	0xe3, 0x78, 0x07, 0xfe, 0x8d, 0x68, 0x5b, 0x2e, 0x5f, 0xfa, 0x23, 0x98, 0x93, 0x9d, 0x54, 0xf6,
	0x92, 0x7d, 0x27, 0x31, 0xa7, 0xad, 0xc5, 0xf4, 0x02, 0x16, 0xb5, 0x14, 0xa5, 0x54, 0xf6, 0x74,
	0x61, 0xb6, 0x4c, 0x37, 0x2d, 0x16, 0xcf, 0x5b, 0xcb, 0xf1, 0x31, 0x17, 0xdf, 0x4f, 0x6a, 0x7d,
	0x03, 0x51, 0x83, 0x2f, 0x83, 0x58, 0x98, 0x91, 0x74, 0x34, 0x8a, 0x7f, 0x65, 0xce, 0x2c, 0x73,
	0xcf, 0x2c, 0xcb, 0x62, 0x70, 0x9f, 0xee, 0xe8, 0x7f, 0xf0, 0x7a, 0x55, 0x4a, 0xd2, 0x71, 0xd4,
	0xd5, 0x14, 0xe9, 0xf8, 0xc7, 0x7e, 0x61, 0x3f, 0xc2, 0xd5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0x39, 0xd4, 0x1b, 0x21, 0x02, 0x00, 0x00,
}
